### ISSUE TITLE
Random login with LinkedIn

### ISSUE THREAD

**Issue by vi2606** [ankitsejwal/Lyndor#66]
Hello!
Im getting this crashes, Lynda ask for sign in via LinkedIn.

Thanks 

Traceback (most recent call last):
  File "run.py", line 137, in <module>
    main()
  File "run.py", line 36, in main
    schedule_download(url)
  File "run.py", line 55, in schedule_download
    download_course(url)
  File "run.py", line 118, in download_course
    exercise_file.download(url, course_folder_path, cookie_path)
  File "/home/vi420/Downloads/Lyndor/module/exercise_file.py", line 36, in download
    regular_login(url, course_folder, driver)
  File "/home/vi420/Downloads/Lyndor/module/exercise_file.py", line 177, in regular_login
    EC.presence_of_element_located((By.CSS_SELECTOR, "#password-input")))
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/support/wait.py", line 71, in until
    value = method(self._driver)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/support/expected_conditions.py", line 63, in __call__
    return _find_element(driver, self.locator)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/support/expected_conditions.py", line 401, in _find_element
    raise e
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=69.0.3497.100)
  (Driver info: chromedriver=2.35.528139 (47ead77cb35ad2a9a83248b292151462a66cd881),platform=Linux 4.15.0-34-generic x86_64)

**Comment by vi2606** [comment]
It worked before, last few days I would find myself logged out of Lynda(in browser). Yesterday Lynda wouldnt let me log in with Lynda credentials, I had to use sign in with LinkedIn. 
I was wondering that they are changing something.

As I said, everything worked till today.

Btw, where I put those chrome options tha you sent me(I never programmed Python )?

Thanks

**Comment by ankitsejwal** [comment]
```python
# open exercise_file.py and look at line 31
chrome = webdriver.Chrome('/usr/local/bin/chromedriver', chrome_options=chrome_options)
# '/usr/local/bin/chromedriver', should be missing which is the path for chrome driver

```
So do you mean you were able to download exercise file and all of sudden it stopped working, that's weird didn't happen to me yet but yeah after LinkedIn bought Lynda they are changing a lot of things in order to tailor it for LinkedIn Learning.

**Comment by vi2606** [comment]
My file:
`    if read.exfile_download_method == "aria2":
            options.add_argument('headless')
        
        options.add_argument("--window-size=1300x744")
        driver = webdriver.Chrome(chrome_options=options)
    else:
        sys.exit('Choose either chrome or firefox in settings.json to download exercise file')          `

Exactly, I setup Lyndor no prob, used Lynda login credentials and downloaded flawlessly.
And then errors appeared this morning. 
And earlier I used to keep Lynda tab open for months and never asked to login again. 
Last maybe a week or so I am getting logouts.
This morning, as I said, I had to login with LinkedIn.

We will see

**Comment by ankitsejwal** [comment]
@vi2606 sorry for the delay, are you still getting this error?

**Comment by vi2606** [comment]
I didnt use Lynda as much but for about last 10 logins, I was always directed to use Linkedin credentials when trying to log in with my Lynda account credentials...
When I use username/pass option with Lyndor, i get an error.

![screenshot from 2018-10-04 08-00-30](https://user-images.githubusercontent.com/36774734/46455598-11b24c00-c7ac-11e8-910b-12360b9c37ce.png)
