### ISSUE TITLE
File not found for some video files

### ISSUE THREAD

**Issue by banpie** [ankitsejwal/Lyndor#74]
## Please follow the guide below

- You will be asked some question, please read them **carefully**
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/ankitsejwal/Lyndor/blob/master/README.md)

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with Lyndor) :beetle: 
- [ ] Feature request (request for a new functionality) :point_up:
- [X ] Question :question: I know about the cookie methos，some of the video have been downloaded，but other are not。
- [ ] Other

![image](https://user-images.githubusercontent.com/9192763/47540852-8ee36380-d909-11e8-82d4-351c6472cf91.png)

---

### If the purpose of this *issue* is a *bug report*,  or you are not completely sure then provide the full terminal output as follows:
Copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
python3 run.py
             .
           .d$ .
           d$$  :
          .$$$
          :$$$   :            Download multiple courses
          $$$$   :          at a time, just paste all the
          $$$$   :            urls in Bulk Download.txt
         .$$$$                
         :$$$$    :
         $$$$$    :
         :    $$$$$      Change preferences in settings.json
         :    $$$$$        Run python settings/settings.py
        .:    $$$$$.
       / :    $$$$: \
      /  :    $$$$:  \
     '        $$$$`   '
     |   /:   $$$$\   |
     |  /     $$$` \  |
     |_/   :__$$P   \_|    🏄

1. Paste course url or
2. Press enter for Bulk Download
https://www.lynda.com/Marketing-tutorials/Connecting-customers-online/693114/760680-4.html

🍪  Using latest cookie file: /Users/aban/Downloads/cookies.txt

creating course folder at: /Users/aban/Movies/Lynda/Connecting with customers online

Course Name	Connecting with customers online
Course id	693114
Author Name	Brad Batesole
Topics		#Content Marketing	#Small Business Marketing	#Marketing	#Online Marketing	#SEO	
Softwares	None
Duration	4h 43m
Release Date	6/29/2018
Downloaded On	26/October/2018
Course URL	https://www.lynda.com/Marketing-tutorials/Connecting-customers-online/693114/760680-4.html

🌟  info.txt created

Creating Chapters:

00. Introduction
01. Digital Marketing Strategy
02. Exploring Digital Marketing
03. Starting with Your Website
04. Foundations of Analytics
05. Search Engine Optimization
06. Search and Display Marketing
07. Social Media Marketing
08. Video Marketing
09. Email Marketing
10. Content Marketing
11. Mobile Marketing
12. Expanding Your Digital Marketing Skills
13. Influencer Marketing
14. Conclusion

✅  15 chapters created!!

👍🏻  CONTENT.md created.

[lynda] 760680: Downloading video JSON
[lynda] 760680: Checking 0-360 video format URL
[lynda] 760680: Checking 0-540 video format URL
[lynda] 760680: Checking 0-720 video format URL
[lynda] 760680: Checking 1-360 video format URL
[lynda] 760680: Checking 1-540 video format URL
[lynda] 760680: Checking 1-720 video format URL
[info] Writing video subtitles to: /Users/aban/Movies/Lynda/Connecting with customers online/NA - Connecting with customers online.en.srt
[download] Destination: /Users/aban/Movies/Lynda/Connecting with customers online/NA - Connecting with customers online.mp4
[download] 100% of 23.18MiB in 01:46

🔰  Renaming video/subtitle files


Videos available: 63
Videos downloaded: 1

🔰  Moving files inside: 00. Introduction
🤕  File not found: 01 - Connecting with customers online.mp4
🤕  File not found: 02 - What is online marketing.mp4
🔰  Moving files inside: 01. Digital Marketing Strategy
🤕  File not found: 03 - The importance of defining three strategies.mp4
🤕  File not found: 04 - Building a business strategy.mp4
🤕  File not found: 05 - Building a brand strategy.mp4
🤕  File not found: 06 - Building a marketing strategy.mp4
🔰  Moving files inside: 02. Exploring Digital Marketing
🤕  File not found: 07 - Definitions and terminology.mp4
🤕  File not found: 08 - Components of digital marketing.mp4
🤕  File not found: 09 - The digital marketing landscape.mp4
🤕  File not found: 10 - The marketing funnel.mp4
🤕  File not found: 11 - The buyer journey.mp4
🔰  Moving files inside: 03. Starting with Your Website
🤕  File not found: 12 - What makes a website effective.mp4
🤕  File not found: 13 - Choosing a domain name.mp4
🤕  File not found: 14 - Selecting a designer or developer.mp4
🤕  File not found: 15 - Building a site yourself.mp4
🤕  File not found: 16 - Making your website convert.mp4
🤕  File not found: 17 - Creating engaging web copy.mp4
🤕  File not found: 18 - Choosing responsive design.mp4
🔰  Moving files inside: 04. Foundations of Analytics
🤕  File not found: 19 - Introduction to measuring data.mp4
🤕  File not found: 20 - How online analytics work.mp4
🤕  File not found: 21 - Tracking your campaigns.mp4
🤕  File not found: 22 - Using goal tracking.mp4
🤕  File not found: 23 - Looking at a conversion funnel.mp4
🤕  File not found: 24 - Defining your KPIs.mp4
🤕  File not found: 25 - A look at attribution models.mp4
🔰  Moving files inside: 05. Search Engine Optimization
🤕  File not found: 26 - How SEO works.mp4
🤕  File not found: 27 - Essential optimization techniques.mp4
🤕  File not found: 28 - Configuring Google Search Console.mp4
🤕  File not found: 29 - Conducting keyword research.mp4
🤕  File not found: 30 - Conducting a quick site audit.mp4
🤕  File not found: 31 - Crafting a content strategy.mp4
🤕  File not found: 32 - Leveraging local SEO.mp4
🤕  File not found: 33 - Choosing to hire a professional.mp4
🔰  Moving files inside: 06. Search and Display Marketing
🤕  File not found: 34 - Introduction to search and display.mp4
🤕  File not found: 35 - Signing up for an AdWords account.mp4
🤕  File not found: 36 - Understanding the AdWords structure.mp4
🤕  File not found: 37 - Launching text search ads.mp4
🤕  File not found: 38 - Launching display search ads.mp4
🤕  File not found: 39 - Deciding on your budget.mp4
🤕  File not found: 40 - A look at reporting.mp4
🤕  File not found: 41 - Generating reports.mp4
🔰  Moving files inside: 07. Social Media Marketing
🤕  File not found: 42 - Building a social media marketing plan.mp4
🤕  File not found: 43 - Who's using social media.mp4
🤕  File not found: 44 - Marketing with Facebook.mp4
🤕  File not found: 45 - Marketing with Twitter.mp4
🤕  File not found: 46 - Marketing with LinkedIn.mp4
🤕  File not found: 47 - Marketing with Pinterest.mp4
🔰  Moving files inside: 08. Video Marketing
🤕  File not found: 48 - The impact of video marketing.mp4
🤕  File not found: 49 - Getting started with video marketing.mp4
🤕  File not found: 50 - Creating compelling content.mp4
🤕  File not found: 51 - Promoting videos on YouTube.mp4
🔰  Moving files inside: 09. Email Marketing
🤕  File not found: 52 - Understanding email marketing.mp4
🤕  File not found: 53 - Creating an email marketing plan.mp4
🤕  File not found: 54 - Tools to launch successful campaigns.mp4
🤕  File not found: 55 - Measuring the success of email.mp4
🔰  Moving files inside: 10. Content Marketing
🤕  File not found: 56 - The mobile marketing landscape.mp4
🤕  File not found: 57 - What is content marketing.mp4
🔰  Moving files inside: 11. Mobile Marketing
🤕  File not found: 58 - Mobile applications.mp4
🤕  File not found: 59 - Creating a content planning model.mp4
🔰  Moving files inside: 12. Expanding Your Digital Marketing Skills
🤕  File not found: 60 - Running A_B marketing tests.mp4
🔰  Moving files inside: 13. Influencer Marketing
🤕  File not found: 61 - Introduction to influencer marketing.mp4
🤕  File not found: 62 - Finding and engaging influencers.mp4
🔰  Moving files inside: 14. Conclusion
🤕  File not found: 63 - Next steps.mp4


Exercise file is available to download
settings.json says you do not want to download ex-file -> 'download_exercise_file': false

 ----------------------------
              ^__^
              (oo)\_______
 Download     (__)\       )\/\🏁
 Successful       ||----w |
                  ||     ||

The whole process took 0:02:25.13
```
---

### The issue was encountered on:       :computer:
- [ X] MacOS
- [ ] Windows
- [ ] Linux

### Login method:
- [ ] Regular login (username + password)
- [X ] Organization login (cookies.txt)
- [] cookies.txt + Library login(for exercise file)

### Enter the python version you are using for download. Find your python version by typing in terminal `python -V`
- python (3.6)

---

### If the purpose of this *issue* is a *bug report* please provide all kinds of example URLs where you encountered issues (replace following example URLs by **yours**):
- https://www.lynda.com/Business-Software-tutorials/Time-Management-Tips-Weekly/440668-2.html
- https://www.lynda.com/jQuery-tutorials/jQuery-Creating-Plugins/364350-2.html

---

### Description of your *issue*, suggested a solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the description is worded well enough to be understood. Provide as much context and examples as possible.

**Comment by frostebite** [comment]
use cookie auth

**Comment by Modulus16** [comment]
I seem to have a similar issue. I'm using cookie auth and have tired both the chrome and firefox webdrivers. Same results each time. I'm on macOS and running python 3.7.3. I've also tried with and without using aria2c. I get the same results every time.

Here's my output:

```
             .
           .d$ .
           d$$  :
          .$$$
          :$$$   :            Download multiple courses
          $$$$   :          at a time, just paste all the
          $$$$   :            urls in Bulk Download.txt
         .$$$$                
         :$$$$    :
         $$$$$    :
         :    $$$$$      Change preferences in settings.json
         :    $$$$$        Run python settings/settings.py
        .:    $$$$$.
       / :    $$$$: \
      /  :    $$$$:  \
     '        $$$$`   '
     |   /:   $$$$\   |
     |  /     $$$` \  |
     |_/   :__$$P   \_|    🏄

1. Paste course url or
2. Press enter for Bulk Download
https://www.lynda.com/Sheets-tutorials/Google-Sheets-Essential-Training/163414-2.html

🍪  Using latest cookie file: /Users/x/Downloads/cookies.txt

creating course folder at: /Users/x/Movies/Lynda/Google Sheets Essential Training

Course Name	Google Sheets Essential Training
Course id	163414
Author Name	Sally Norred
Topics		#Business	#Productivity	#Spreadsheets	
Softwares	#Sheets	#Google Sheets	
Duration	3h 4m
Release Date	8/26/2014
Downloaded On	06/April/2019
Course URL	https://www.lynda.com/Sheets-tutorials/Google-Sheets-Essential-Training/163414-2.html

🌟  info.txt created

Creating Chapters:

00. Introduction
01. Getting Started with Google Sheets
02. Creating Spreadsheets
03. Editing Spreadsheets
04. Viewing and Printing Spreadsheets
05. Formatting Spreadsheets
06. Working with Spreadsheet Data
07. Collaborating with Google Sheets
08. Using the Google Sheets Mobile App
09. Conclusion

✅  10 chapters created!!

👍🏻  CONTENT.md created.

[lynda:course] 163414: Downloading course JSON
WARNING: 45 videos are only available for members (or paid members) and will not be downloaded. Use --username and --password options to provide lynda.com account credentials.
[download] Downloading playlist: Google Sheets Essential Training
[lynda:course] playlist Google Sheets Essential Training: Collected 7 video ids (downloading 7 of them)
[download] Downloading video 1 of 7
[lynda] 187741: Downloading video JSON
[lynda] 187741: Checking 0-540 video format URL
[lynda] 187741: Checking 0-720 video format URL
[lynda] 187741: Checking 0-360 video format URL
[lynda] 187741: Checking 1-540 video format URL
[lynda] 187741: Checking 1-720 video format URL
[lynda] 187741: Checking 1-360 video format URL
[info] Writing video subtitles to: /Users/x/Movies/Lynda/Google Sheets Essential Training/1 - Welcome.en.srt
[download] Destination: /Users/x/Movies/Lynda/Google Sheets Essential Training/1 - Welcome.mp4

04/06 17:11:02 [NOTICE] Downloading 1 item(s)

04/06 17:11:03 [NOTICE] Download complete: /Users/x/Movies/Lynda/Google Sheets Essential Training/1 - Welcome.mp4.part

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
97cb29|OK  |    12MiB/s|/Users/x/Movies/Lynda/Google Sheets Essential Training/1 - Welcome.mp4.part

Status Legend:
(OK):download completed.
[aria2c] Downloaded 4781380 bytes
[download] 100% of 4.56MiB in 00:00
[download] Downloading video 2 of 7
[lynda] 187742: Downloading video JSON
[lynda] 187742: Checking 0-540 video format URL
[lynda] 187742: Checking 0-720 video format URL
[lynda] 187742: Checking 0-360 video format URL
[lynda] 187742: Checking 1-540 video format URL
[lynda] 187742: Checking 1-720 video format URL
[lynda] 187742: Checking 1-360 video format URL
[info] Writing video subtitles to: /Users/x/Movies/Lynda/Google Sheets Essential Training/2 - Importing exercise files to Google Sheets.en.srt
[download] Destination: /Users/x/Movies/Lynda/Google Sheets Essential Training/2 - Importing exercise files to Google Sheets.mp4

04/06 17:11:04 [NOTICE] Downloading 1 item(s)

04/06 17:11:05 [NOTICE] Download complete: /Users/x/Movies/Lynda/Google Sheets Essential Training/2 - Importing exercise files to Google Sheets.mp4.part

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
4cdc10|OK  |    11MiB/s|/Users/x/Movies/Lynda/Google Sheets Essential Training/2 - Importing exercise files to Google Sheets.mp4.part

Status Legend:
(OK):download completed.
[aria2c] Downloaded 3465883 bytes
[download] 100% of 3.31MiB in 00:00
[download] Downloading video 3 of 7
[lynda] 806177: Downloading video JSON
[lynda] 806177: Checking 0-720 video format URL
[lynda] 806177: Checking 0-540 video format URL
[lynda] 806177: Checking 0-360 video format URL
[lynda] 806177: Checking 1-720 video format URL
[lynda] 806177: Checking 1-540 video format URL
[lynda] 806177: Checking 1-360 video format URL
[info] Writing video subtitles to: /Users/x/Movies/Lynda/Google Sheets Essential Training/3 - What's new in Google Sheets.en.srt
[download] Destination: /Users/x/Movies/Lynda/Google Sheets Essential Training/3 - What's new in Google Sheets.mp4

04/06 17:11:07 [NOTICE] Downloading 1 item(s)

04/06 17:11:07 [NOTICE] Allocating disk space. Use --file-allocation=none to disable it. See --file-allocation option in man page for more details.

04/06 17:11:07 [NOTICE] Download complete: /Users/x/Movies/Lynda/Google Sheets Essential Training/3 - What's new in Google Sheets.mp4.part

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
e22bec|OK  |    36MiB/s|/Users/x/Movies/Lynda/Google Sheets Essential Training/3 - What's new in Google Sheets.mp4.part

Status Legend:
(OK):download completed.
[aria2c] Downloaded 17149493 bytes
[download] 100% of 16.36MiB in 00:00
[download] Downloading video 4 of 7
[lynda] 187755: Downloading video JSON
[lynda] 187755: Checking 0-540 video format URL
[lynda] 187755: Checking 0-720 video format URL
[lynda] 187755: Checking 0-360 video format URL
[lynda] 187755: Checking 1-540 video format URL
[lynda] 187755: Checking 1-720 video format URL
[lynda] 187755: Checking 1-360 video format URL
[info] Writing video subtitles to: /Users/x/Movies/Lynda/Google Sheets Essential Training/4 - Importing and converting Excel or OpenOffice spreadsheets.en.srt
[download] Destination: /Users/x/Movies/Lynda/Google Sheets Essential Training/4 - Importing and converting Excel or OpenOffice spreadsheets.mp4

04/06 17:11:09 [NOTICE] Downloading 1 item(s)

04/06 17:11:09 [NOTICE] Allocating disk space. Use --file-allocation=none to disable it. See --file-allocation option in man page for more details.

04/06 17:11:10 [NOTICE] Download complete: /Users/x/Movies/Lynda/Google Sheets Essential Training/4 - Importing and converting Excel or OpenOffice spreadsheets.mp4.part

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
4e2077|OK  |    21MiB/s|/Users/x/Movies/Lynda/Google Sheets Essential Training/4 - Importing and converting Excel or OpenOffice spreadsheets.mp4.part

Status Legend:
(OK):download completed.
[aria2c] Downloaded 10868896 bytes
[download] 100% of 10.37MiB in 00:00
[download] Downloading video 5 of 7
[lynda] 187762: Downloading video JSON
[lynda] 187762: Checking 0-540 video format URL
[lynda] 187762: Checking 0-720 video format URL
[lynda] 187762: Checking 0-360 video format URL
[lynda] 187762: Checking 1-540 video format URL
[lynda] 187762: Checking 1-720 video format URL
[lynda] 187762: Checking 1-360 video format URL
[info] Writing video subtitles to: /Users/x/Movies/Lynda/Google Sheets Essential Training/5 - Using keyboard shortcuts.en.srt
[download] Destination: /Users/x/Movies/Lynda/Google Sheets Essential Training/5 - Using keyboard shortcuts.mp4

04/06 17:11:12 [NOTICE] Downloading 1 item(s)

04/06 17:11:12 [NOTICE] Allocating disk space. Use --file-allocation=none to disable it. See --file-allocation option in man page for more details.

04/06 17:11:12 [NOTICE] Download complete: /Users/x/Movies/Lynda/Google Sheets Essential Training/5 - Using keyboard shortcuts.mp4.part

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
3d9165|OK  |    26MiB/s|/Users/x/Movies/Lynda/Google Sheets Essential Training/5 - Using keyboard shortcuts.mp4.part

Status Legend:
(OK):download completed.
[aria2c] Downloaded 9971267 bytes
[download] 100% of 9.51MiB in 00:00
[download] Downloading video 6 of 7
[lynda] 187763: Downloading video JSON
[lynda] 187763: Checking 0-540 video format URL
[lynda] 187763: Checking 0-720 video format URL
[lynda] 187763: Checking 0-360 video format URL
[lynda] 187763: Checking 1-540 video format URL
[lynda] 187763: Checking 1-720 video format URL
[lynda] 187763: Checking 1-360 video format URL
[info] Writing video subtitles to: /Users/x/Movies/Lynda/Google Sheets Essential Training/6 - Creating a series of numbers or dates.en.srt
[download] Destination: /Users/x/Movies/Lynda/Google Sheets Essential Training/6 - Creating a series of numbers or dates.mp4

04/06 17:11:14 [NOTICE] Downloading 1 item(s)
[#f5866e 0B/0B CN:1 DL:0B]                                                                                                                                                                                     
04/06 17:11:18 [NOTICE] Allocating disk space. Use --file-allocation=none to disable it. See --file-allocation option in man page for more details.

04/06 17:11:18 [NOTICE] Download complete: /Users/x/Movies/Lynda/Google Sheets Essential Training/6 - Creating a series of numbers or dates.mp4.part

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
f5866e|OK  |   9.5MiB/s|/Users/x/Movies/Lynda/Google Sheets Essential Training/6 - Creating a series of numbers or dates.mp4.part

Status Legend:
(OK):download completed.
[aria2c] Downloaded 6548230 bytes
[download] 100% of 6.24MiB in 00:04
[download] Downloading video 7 of 7
[lynda] 187769: Downloading video JSON
[lynda] 187769: Checking 0-540 video format URL
[lynda] 187769: Checking 0-720 video format URL
[lynda] 187769: Checking 0-360 video format URL
[lynda] 187769: Checking 1-540 video format URL
[lynda] 187769: Checking 1-720 video format URL
[lynda] 187769: Checking 1-360 video format URL
[info] Writing video subtitles to: /Users/x/Movies/Lynda/Google Sheets Essential Training/7 - Freezing rows and columns.en.srt
[download] Destination: /Users/x/Movies/Lynda/Google Sheets Essential Training/7 - Freezing rows and columns.mp4

04/06 17:11:20 [NOTICE] Downloading 1 item(s)

04/06 17:11:21 [NOTICE] Download complete: /Users/x/Movies/Lynda/Google Sheets Essential Training/7 - Freezing rows and columns.mp4.part

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
0cf541|OK  |    13MiB/s|/Users/x/Movies/Lynda/Google Sheets Essential Training/7 - Freezing rows and columns.mp4.part

Status Legend:
(OK):download completed.
[aria2c] Downloaded 4890277 bytes
[download] 100% of 4.66MiB in 00:00
[download] Finished downloading playlist: Google Sheets Essential Training

🔰  Renaming video/subtitle files


Videos available: 52
Videos downloaded: 7

🔰  Moving files inside: 00. Introduction
🤕  File not found: 01 - Welcome.mp4
🤕  File not found: 02 - Importing exercise files to Google Sheets.mp4
🤕  File not found: 03 - What's new in Google Sheets.mp4
🔰  Moving files inside: 01. Getting Started with Google Sheets
🤕  File not found: 04 - What is Google Sheets.mp4
🤕  File not found: 05 - Accessing Google Sheets with your account.mp4
🤕  File not found: 06 - Understanding common Google Sheets terminology.mp4
🤕  File not found: 07 - Navigating Google Sheets.mp4
🔰  Moving files inside: 02. Creating Spreadsheets
🤕  File not found: 08 - Creating, naming, and saving a spreadsheet.mp4
🤕  File not found: 09 - Renaming a spreadsheet.mp4
🤕  File not found: 10 - Copying a spreadsheet.mp4
🤕  File not found: 11 - Moving a spreadsheet.mp4
🤕  File not found: 12 - Deleting a spreadsheet.mp4
🤕  File not found: 13 - Importing and converting Excel or OpenOffice spreadsheets.mp4
🤕  File not found: 14 - Importing and converting .csv, .tsv, .tab, and .txt data files.mp4
🔰  Moving files inside: 03. Editing Spreadsheets
🤕  File not found: 15 - Entering and editing cell content.mp4
🤕  File not found: 16 - Inserting, deleting, and clearing rows and columns.mp4
🤕  File not found: 17 - Moving rows, columns, and cells.mp4
🤕  File not found: 18 - Working with multiple sheets.mp4
🤕  File not found: 19 - Using keyboard shortcuts.mp4
🤕  File not found: 20 - Creating a series of numbers or dates.mp4
🤕  File not found: 21 - Using Find and Replace.mp4
🤕  File not found: 22 - Entering hyperlinks.mp4
🤕  File not found: 23 - Inserting images into spreadsheets.mp4
🔰  Moving files inside: 04. Viewing and Printing Spreadsheets
🤕  File not found: 24 - Using the View menu.mp4
🤕  File not found: 25 - Freezing rows and columns.mp4
🤕  File not found: 26 - Hiding rows, columns, and sheets.mp4
🤕  File not found: 27 - Publishing a spreadsheet to the web.mp4
🤕  File not found: 28 - Printing a spreadsheet.mp4
🤕  File not found: 29 - Customizing your printed spreadsheet.mp4
🔰  Moving files inside: 05. Formatting Spreadsheets
🤕  File not found: 30 - Formatting cell, row, and column data.mp4
🤕  File not found: 31 - Google Sheets formatting tips.mp4
🤕  File not found: 32 - Using conditional formatting.mp4
🤕  File not found: 33 - Creating a spreadsheet from a template.mp4
🔰  Moving files inside: 06. Working with Spreadsheet Data
🤕  File not found: 34 - Sorting data on a spreadsheet.mp4
🤕  File not found: 35 - Using Quick Sum.mp4
🤕  File not found: 36 - Using formulas and functions.mp4
🤕  File not found: 37 - Using IF functions and nested functions.mp4
🤕  File not found: 38 - Referencing data from other sheets.mp4
🤕  File not found: 39 - Creating charts in Google Sheets.mp4
🤕  File not found: 40 - Using filters and creating filter views.mp4
🤕  File not found: 41 - Using pivot tables.mp4
🤕  File not found: 42 - Automating tasks with recorded macros.mp4
🔰  Moving files inside: 07. Collaborating with Google Sheets
🤕  File not found: 43 - Sharing a spreadsheet file with other people.mp4
🤕  File not found: 44 - Working with Google Sheets that are shared with you.mp4
🤕  File not found: 45 - Working with spreadsheet revisions.mp4
🤕  File not found: 46 - Commenting on a spreadsheet.mp4
🤕  File not found: 47 - Emailing spreadsheet collaborators.mp4
🤕  File not found: 48 - Collaborating simultaneously and using Google Chat.mp4
🔰  Moving files inside: 08. Using the Google Sheets Mobile App
🤕  File not found: 49 - Installing the Google Sheets mobile app.mp4
🤕  File not found: 50 - Navigating the Google Sheets mobile app.mp4
🤕  File not found: 51 - Working with spreadsheets on the Google Sheets mobile app.mp4
🔰  Moving files inside: 09. Conclusion
🤕  File not found: 52 - Helpful resources.mp4


Exercise file is available to download

library card no. and card pin. entered successfully....
launching desired course page ....
Traceback (most recent call last):
  File "/Users/x/Applications/Lyndor/run.py", line 137, in <module>
    main()
  File "/Users/x/Applications/Lyndor/run.py", line 39, in main
    schedule_download(url)
  File "/Users/x/Applications/Lyndor/run.py", line 55, in schedule_download
    download_course(url)
  File "/Users/x/Applications/Lyndor/run.py", line 123, in download_course
    exercise_file.download(url, course_folder_path, cookie_path)
  File "/Users/x/Applications/Lyndor/module/exercise_file.py", line 54, in download
    use_selenium(url, course_folder, driver)
  File "/Users/x/Applications/Lyndor/module/exercise_file.py", line 76, in use_selenium
    EC.presence_of_element_located((By.CSS_SELECTOR, "html.no-touch.member.loaded")))
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
```
