### ISSUE TITLE
ERROR: None: Failed to parse JSON  (caused by JSONDecodeError('Expecting property name enclosed in double quotes: line 1 column 3 (char 2)'))

### ISSUE THREAD

**Issue by ndraden** [ankitsejwal/Lyndor#84]
i have error when download videos, how to solve this? just some videos, everything is fine.
👍🏻  CONTENT.md created.

[lynda] 737619: Downloading video JSON
[lynda] 737619: Checking 0-720 video format URL
[lynda] 737619: Checking 0-540 video format URL
[lynda] 737619: Checking 0-360 video format URL
[lynda] 737619: Checking 1-720 video format URL
[lynda] 737619: Checking 1-540 video format URL
[lynda] 737619: Checking 1-360 video format URL
ERROR: None: Failed to parse JSON  (caused by JSONDecodeError('Expecting property name enclosed in double quotes: line 1 column 3 (char 2)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

🔰  Renaming video/subtitle files

## Please follow the guide below

- You will be asked some question, please read them **carefully**
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through the [README](https://github.com/ankitsejwal/Lyndor/blob/master/README.md)

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with Lyndor) :beetle: 
- [ ] Feature request (request for a new functionality) :point_up:
- [ ] Question :question:
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*,  or you are not completely sure then provide the full terminal output as follows:
Copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
Traceback (most recent call last):
  File "/Users/pi/Projects/lyndor/run.py", line 130, in <module>
    main()
  File "/Users/pi/Projects/lyndor/run.py", line 35, in main
    schedule_download(url)
  File "/Users/pi/Projects/lyndor/run.py", line 51, in schedule_download
    download_course(url)
  File "/Users/pi/Projects/lyndor/run.py", line 78, in download_course
    course_folder_path = save.course_path(url, lynda_folder_path)
NameError: global name 'save' is not defined
```
---

### The issue was encountered on:       :computer:
- [ ] MacOS
- [ ] Windows
- [ ] Linux

### Login method:
- [ ] Regular login (username + password)
- [ ] Organization login (cookies.txt)
- [ ] cookies.txt + Library login(for exercise file)

### Enter the python version you are using for download. Find your python version by typing in terminal `python -V`
- python (version) [replace (version) with your python version like: python 3.6.3]

---

### If the purpose of this *issue* is a *bug report* please provide all kinds of example URLs where you encountered issues (replace following example URLs by **yours**):
- https://www.lynda.com/Business-Software-tutorials/Time-Management-Tips-Weekly/440668-2.html
- https://www.lynda.com/jQuery-tutorials/jQuery-Creating-Plugins/364350-2.html

---

### Description of your *issue*, suggested a solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the description is worded well enough to be understood. Provide as much context and examples as possible.

**Comment by jawidjrs** [comment]
I think this error might be occurred because of the title of the course has special characters in it. I tried my self this : "Become a CompTIA A+ (220-1001 and 220-1002) Certified Technician" and got the same error. but this "Motivating Your Team to Learn" and this "Motivating Your Team to Learn" were completely normal download without any error.
