### ISSUE TITLE
Cant download ex files 

### ISSUE THREAD

**Issue by joshyjoshh** [ankitsejwal/Lyndor#85]
is there a way to download exercise files? 

sorry for the noob question, i've spent a few hours trying to get the download to work as my paths were messed up.

i am using email/pw login also have a cookie.txt file on downloads.

i am able to download videos fine but havnt been able to do anything with the exercise files

Please point me in the right direction,

videos/subtitles moved to appropriate chapters successfully.

Exercise file is available to download
Traceback (most recent call last):
  File "desktop/Lyndor/run.py", line 137, in <module>
    main()
  File "desktop/Lyndor/run.py", line 39, in main
    schedule_download(url)
  File "desktop/Lyndor/run.py", line 55, in schedule_download
    download_course(url)
  File "desktop/Lyndor/run.py", line 118, in download_course
    exercise_file.download(url, course_folder_path, cookie_path)
  File "/Users/Villa/Desktop/Lyndor/module/exercise_file.py", line 31, in download
    driver = webdriver.Chrome(chrome_options=options)
  File "/Users/Villa/PycharmProjects/python/venv/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "/Users/Villa/PycharmProjects/python/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/Users/Villa/PycharmProjects/python/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Users/Villa/PycharmProjects/python/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/Users/Villa/PycharmProjects/python/venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 74
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Mac OS X 10.12.6 x86_64)

**Comment by padillam5** [comment]
you need to actually download chromedriver and geckodriver than add to path with this

# for Mac or Linux -> add the new webdriver directory path to ~/.bash_profile or ~/.bash_rc
export PATH="/path/to/Lyndor/webdriver:$PATH"
