### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by hypxy** [ankitsejwal/Lyndor#94]
Hello.

What is the reason and the solution for this issue below? 
Thanks

```
-> Run-Lyndor.bat file created.

Traceback (most recent call last):
  File "install.py", line 79, in <module>
    save.aria2()
  File "C:\***\Lyndor-master\module\save.py", line 298, in aria2
    aria = requests.get(UnboundLocalError: 
local variable 'requests' referenced before assignment
```

**Comment by yangbaona** [comment]
same problem

**Comment by yangbaona** [comment]
ERROR: Command errored out with exit status 1:
     command: 'c:\python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\yangbaona\\AppData\\Local\\Temp\\pip-install-95od2lqh\\markupsafe_6e8d3475c1a24e909dd6531ef993204b\\setup.py'"'"'; __file__='"'"'C:\\Users\\yangbaona\\AppData\\Local\\Temp\\pip-install-95od2lqh\\markupsafe_6e8d3475c1a24e909dd6531ef993204b\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\yangbaona\AppData\Local\Temp\pip-pip-egg-info-0vcu6zj7'
         cwd: C:\Users\yangbaona\AppData\Local\Temp\pip-install-95od2lqh\markupsafe_6e8d3475c1a24e909dd6531ef993204b\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\yangbaona\AppData\Local\Temp\pip-install-95od2lqh\markupsafe_6e8d3475c1a24e909dd6531ef993204b\setup.py", line 6, in <module>
        from setuptools import setup, Extension, Feature
    ImportError: cannot import name 'Feature' from 'setuptools' (c:\python39\lib\site-packages\setuptools\__init__.py)
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/4d/de/32d741db316d8fdb7680822dd37001ef7a448255de9699ab4bfcbdf4172b/MarkupSafe-1.0.tar.gz#sha256=a6be69091dac236ea9c6bc7d012beab42010fa914c459791d627dad4910eb665 (from https://pypi.org/simple/markupsafe/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement MarkupSafe==1.0 (from versions: 0.9, 0.9.1, 0.9.2, 0.9.3, 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.20, 0.21, 0.22, 0.23, 1.0, 1.1.0, 1.1.1, 2.0.0a1, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.0.1)
ERROR: No matching distribution found for MarkupSafe==1.0

>>> Courses will be saved at -> C:\Users\yangbaona\Videos/Lynda

-> settings.json file created at Lyndor/settings/static/js/settings.json

>>> Lynda folder already exists

-> aliases.bat file created.

-> Bulk Download.txt file created successfully.

-> Run-Lyndor.bat file created.

Traceback (most recent call last):
  File "C:\Python39\libs\Lyndor-master\install.py", line 79, in <module>
    save.aria2()
  File "C:\Python39\libs\Lyndor-master\module\save.py", line 298, in aria2
    aria =requests.get(
UnboundLocalError: local variable 'requests' referenced before assignment
